### ISSUE TITLE
[Bug] Disable Homebar when the keyboard is active. 

### ISSUE THREAD

**Issue by iDonev** [binksxela/LittleXS#10]
Hi

The Homebar functionality clashes when you use a keyboard like SwiftKey. In SwiftKey you change languages by swiping on the space bar. This is the exact gesture for quickly switching between apps via the Homebar. As such, please consider adding the option to disable all Homebar-related functionality when the keyboard is present. 

Thanks!

**Comment by ryannair05** [comment]
You can install DisableSwipeX from this repo to fix the problem : http://cydia.ichitaso.com/
