### ISSUE TITLE
[Feature Request] Add iPhone 8-style fast app switching. 

### ISSUE THREAD

**Issue by iDonev** [binksxela/LittleXS#12]
Hi,

Please allow us to reactivate the fast app switching behavior that is present on the iPhone 8 and earlier where you 3D-Touch on the left side of the screen.

Thanks!

Best Regards,
Iskren

**Comment by ryannair05** [comment]
This 3D-Touch behavior is not needed with the iPhone X gestures enabled, as you can just swipe on the bottom portion of an app to move throughout the app switcher. A video of this working can be found here, (33 seconds in) : https://www.youtube.com/embed/0-kZrK3RtGA?start=33
