### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by voriondev** [binksxela/LittleXS#15]
**Describe the bug**
LittleXS Settings not showing up in device settings

**Please complete the following information:**
 - Device: iPhone 8 Plus
 - iOS Version: iOS 12.4

**Additional context**
LittleXS is the only thing I have since I jailbreaked. I would like to disable the iPhone X Keyboard but I can't as far as settings are not available.. :/

**Comment by ryannair05** [comment]
Make sure "PreferenceLoader" is installed on your device. If you get the settings to work, an option to disable the iPhone X keyboard will be available.

**Comment by voriondev** [comment]
It did work, thank you.

A good idea would be to add it to dependencies list, as it is not specified on the tweak page / not installed with the packet !
