### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Torpis** [binksxela/LittleXS#16]
**Describe the bug**
Gap showing at the top of some apps (eg Mail) when using classic status bar 

**Screenshots**
![95FC5C06-AB4A-4A52-8D13-A0632C43BCD9](https://user-images.githubusercontent.com/6482585/63279789-8c3f6980-c2a1-11e9-8aae-9cb4dce1e3fa.jpeg)

**Please complete the following information:**
 - Device: 6s
 - iOS Version: 12.4

**Additional context**
Using X style bar fixes the issue

**Comment by ryannair05** [comment]
We will release an update later today to fix this issue

**Comment by ryannair05** [comment]
This issue has bee fixed.
