### ISSUE TITLE
[Bug] Can't navigate/click on homescreen after pulling down the spotlight

### ISSUE THREAD

**Issue by anazhd** [binksxela/LittleXS#17]
**Describe the bug**
I always use spotlight to reach for apps and what not. Every time after 3-4 times pulling down the spotlight, I'm unable to navigate to different page of my homescreen

**Please complete the following information:**
 - Device: iPhone 7
 - iOS Version: 12.4
 - LittleXS: 2.4.2

**Additional context**
iPhone 7:
 - Ultrasound
 - Cappd

I tried to replicate this on iPhone 6+ but the bug didn't exist on 6+. So I decided to turn off almost every substrate on iPhone 7, copying exactly the exact iPhone 6+ substrate. The bug still exist on 7. My current work around is to use the one finger swipe up gesture to make it go back to the 1st page of the homescreen, or even one finger swipe up gesture to recent app/multitask screen.

**Comment by haen7** [comment]
I also have this issue on iPhone 6 iOS 12.4.
This only happens when `Rounded App Switcher + X Dock` is enabled.
