### ISSUE TITLE
Springboard freezes 

### ISSUE THREAD

**Issue by atifchy** [binksxela/LittleXS#4]
My springboard starts to freeze after I open spotlight search.

**Comment by binksxela** [comment]
I’m unable to reproduce this issue. May you show me a video of this happening? And also give me your device model, firmware version and tweak list.

**Comment by atifchy** [comment]
Video: https://m.imgur.com/gallery/D7njUtV
Details: After closing the spotlight search, my homescreen froze. So, i lock my device then unlock it to work.  

Tweaklist:
Tweaks

7-zip (POSIX): 16.02-1
Ace High Sierra: 3.0
AdBlock for YouTube: 1.0.7
AppList: 1.5.15~beta1
AppSync Unified: 32.0
APT (apt-key): 1.4.9-1
APT 0.7 Transitional: 1:0-2
APT 1.4 Strict (libapt-pkg): 1.4.9-1
APT Strict (lib): 1.4.9-2
APT Strict: 1.4.9-1
Assuan: 2.5.1-1
AutoBrightnessToggle (CCSupport): 0.1-3
AutoLockToggle (CCSupport): 0.1-2
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BetterCCXI: 1.4.8
Betternet++: 1.0.1.2
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-1
BundleIDsXI: 1.1.0-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
Cappd: 1.0.3
CC On & Off: 0.0.1.1
CCRinger: 2.0.0
CCSupport: 1.2-3
Cephei: 1.13
Cercube for YouTube: 4.2.3
CocoaTop: 2.0.2-1+debug
ConditionalWiFi4: 1.0.0
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
Cr4shed: 2.0.7
Cydia Background Refresh: 1.0.0.1
Cydia Installer: 1.1.32~b12
Cydia Substrate: 0.9.7032
Cydia Translations: 1.1.32~b1
Cylinder: 1.0.6
DarkChrome: 1.1.1.3
Darwin Tools: 1-6
Debian Packager: 1.18.25-11
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Dragspring: 1.2.1
Essential: 0-1
EVELYN's Repo Icons: 1.0-3
FacebookDarkMode: 2.3.4
file: 5.35-2
Filza File Manager 64-bit: 3.7.0-18
Find Utilities: 4.6.0-2
Flame: 1.3
Flex 3 Beta: 1:3~Beta62
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
iCleaner Pro: 7.7.2
iOS Firmware: 12.1.2
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~b14.5
KBPreferences: 0.0.6
KSBA: 1.3.5-1
LetMeBlock: 0.0.6.4
libbulletin: 0.1-145
libCercube: 1.1.1
libcolorpicker: 1.6.2-2
libidn2: 6.1.2-1
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libSparkAppList: 1.0.3
libswift4: 4.2.1-2
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LittleXS: 1.5
LocationService (CCSupport): 0.1-3
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MTerminal: 1.4-6
Nettle: 3.4-2
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2r-1
p11-kit: 0.23.12-1
PencilChargingIndicator: 1.2~b6
PhotoManager (iOS 12) k: 1.0.1-2+debug
Placeholder: 1.2.1
PlayMusicOnRecord: 1.0.1
PowerSelector (iOS 11 & 12): 1.1-7
PreferenceLoader: 2.2.4~beta1
Profile Directory: 0-1
readline: 8.0-1
ReProvision: 0.4.2
RocketBootstrap: 1.0.7~beta3
rsync: 3.1.3-2
Safari Plus: 1.6.7
sed: 4.5-1
shell-cmds: 118-8
ShiftCycle: 1.3.2-1
ShortcutEnabler: 1.1.3
Signing Certificate: 0.0.1
SmoothCursor: 1.1.2
SnowBoard: 1.1.7
Spotilife: 1.0
SpringPlus11: 1.2
Substrate Safe Mode: 0.9.6001.1
SwipeExpander: 1.0.11-1
SwipeForMore (Debug): 1.1.9
SwipeSelection Pro: 1.0.3-1
System Info: 2.2.1-10+debug
System Memory Reset Fix: 1.0
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
Textyle: 1.2
Trust Cache Injector: 0.4~b5
TSS Saver: 1.2.0
Tweak Count 2: 1.0.1
tweakCompatible: 0.1.5
TweakConfigurator: 0.3
UIKit Tools: 1.1.13-5
Ultrasound: 1.2.7
unrar: 5.6.4-1
unzip: 6.0-1
XZ Utils: 5.2.4-4
YTStatus: 1.1.1
zip: 2.32-1


Sent from my iPhone

Device: iPhone 6
iOS version: 12.1.2
