### ISSUE TITLE
LS Shortcuts and Apple Pay not working

### ISSUE THREAD

**Issue by ShawnNgDeveloper** [binksxela/LittleXS#6]
The LS Shortcuts do not work on iOS 12.0. (It's probably the way that Apple Programmes the 3d Touch iPhone X LS shortcuts)

Also, Apple Pay doesn't wanna work properly when I have "PadLock" or FaceID thingy enabled. (Apple Pay shows FaceID icon and then TouchID prompt comes up but it doesn't allow me to use my cards)

**Comment by ShawnNgDeveloper** [comment]
Also, the Keyboard height is a bit too low, compared to tweaks like Keyboard X

**Comment by ryannair05** [comment]
Apple Pay is broken with the new bottom inset, it has nothing to do with the padlock. The LS Shortcuts are available if you install both "Jumper" and/or "ShortcutEnabler". 

The keyboard height becomes the regular size of the iPhone X if you install the Barmoji tweak. 

Thank you for the reports.

**Comment by ShawnNgDeveloper** [comment]
Apple Pay works with "new bottom inset" on Versions 1.5 and below but not on Versions 2.0.0 and 2.0.1, and versions 2 and up where Face ID latch thingy where implemented.

**Comment by ShawnNgDeveloper** [comment]
So apparently Barmoji does work
and
Apple Pay does work when I disable new bottom insert, is there any way to get new bottom insert and apple pay working?

**Comment by ryannair05** [comment]
We are working on a fix for Apple Pay currently.

**Comment by ryannair05** [comment]
We have pushed an update to fix Apple Pay

**Comment by ShawnNgDeveloper** [comment]
Thanks! It works great now! Keep up the great work!
