### ISSUE TITLE
Blur header missing + hide status bar in control center option not working

### ISSUE THREAD

**Issue by ExsertWizard** [binksxela/LittleXS#8]
- The blur header, which usually appears when scrolling down the control center, is missing which overlaps the modules with the CC status bar. Neptune can do this as shown in one of the screenshots below.
- The "Hide Status Bar in Control Center" toggle doesn't work. Enabling it doesn't hide the CC status bar.

Screenshots:

Neptune
![image](https://user-images.githubusercontent.com/44066520/59121812-5b909a80-8916-11e9-9daf-5e9c952f954a.png)

LittleXS
![image](https://user-images.githubusercontent.com/44066520/59121855-782cd280-8916-11e9-9eb8-d96d19114975.png)

Device Information:
 - Device: iPhone 5s 
 - iOS Version: iOS 12.1

**Comment by binksxela** [comment]
This has been fixed in the latest version
