### ISSUE TITLE
Status bar shift until it disappeare.

### ISSUE THREAD

**Issue by ballkittipat272** [binksxela/LittleXS#9]
**Describe the bug**
When I open Youtube and Google Map (and I think this bug will happen with all app that can switch landscape&portrait and have optimized status bar layout). Tge status bar will shift up everytime I switch between landscape&portrait mode until status bar disappeared.

**Screenshots**
For video example : https://drive.google.com/file/d/1xWEvC9zgKqpRBXk0gfzqGi7vBh5ro2Ri/view?usp=drivesdk

**Please complete the following information:**
 - Device: iPhone 6s
 - iOS Version: iOS 12.0.1

**Comment by binksxela** [comment]
Thanks for the report, I will look into it.

**Comment by binksxela** [comment]
Fixed in 2.3.1
